spring:
  application:
    name: themis

  datasource:
    url: jdbc:mysql://localhost:3306/themis_db
    username: root
    password: fabrica2024*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

themis:
  jwt:
    secret: TuClaveSecretaSuperSegura123!
    expirationMs: 86400000
    cookieName: themis_ticket

server:
  port: 8082


